source 'http://rubygems.org'

gem 'rails', '3.1.1'
gem 'sqlite3'
gem 'jquery-rails'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'zurb-foundation'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'capybara'
  gem 'spork', '~> 0.9.0.rc'

  # Guard - order dependent for Ubuntu notifications
	gem 'rb-inotify'
	gem 'libnotify'
	gem 'guard-bundler'
	gem 'guard-rspec'
	gem 'guard-spork'	
	gem 'rb-fsevent', :require => false
	gem 'rb-fchange', :require => false
  # gem 'guard-livereload'
end

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

